"""auto update

Revision ID: 5e6f8b508417
Revises: 
Create Date: 2026-03-10 08:53:32.893302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6f8b508417'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('assigned_program', sa.String(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('access_allowed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('exercise_group', sa.String(), nullable=False),
    sa.Column('exercise_group_emoji', sa.String(), nullable=True),
    sa.Column('exercise_group_order', sa.Integer(), nullable=True),
    sa.Column('exercise_name', sa.String(), nullable=False),
    sa.Column('time_reps', sa.String(), nullable=False),
    sa.Column('video_link', sa.String(), nullable=False),
    sa.Column('short_instruction', sa.String(), nullable=True),
    sa.Column('exercise_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###