"""auto update

Revision ID: 631af1a8a7da
Revises: 5e6f8b508417
Create Date: 2026-03-19 04:06:59.186005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631af1a8a7da'
down_revision: Union[str, Sequence[str], None] = '5e6f8b508417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('pain_avg', sa.Integer(), nullable=False),
    sa.Column('pain_spread', sa.String(), nullable=True),
    sa.Column('pain_relief', sa.String(), nullable=True),
    sa.Column('pain_worsen', sa.String(), nullable=True),
    sa.Column('movement', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('exercise_frequency', sa.Integer(), nullable=False),
    sa.Column('how_feeling', sa.String(), nullable=True),
    sa.Column('hard_exercises', sa.String(), nullable=True),
    sa.Column('liked_exercises', sa.String(), nullable=True),
    sa.Column('progress_exercises', sa.String(), nullable=True),
    sa.Column('other_notes', sa.String(), nullable=True),
    sa.Column('entry_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_progress_id'), 'weekly_progress', ['id'], unique=False)
    op.alter_column('patients', 'login_alias',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('patients', 'problem_situation',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'problem_situation',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('patients', 'login_alias',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.drop_index(op.f('ix_weekly_progress_id'), table_name='weekly_progress')
    op.drop_table('weekly_progress')
    # ### end Alembic commands ###